version: 'r4512.1701333759.c5824702b'
services:
  db:
    image: postgres
    volumes:
      - .data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres